name: Build Flutter app

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: true
      # will add android after i figured out how to prevent the crash
      matrix:
        config:
        - name: Windows
          os: windows-latest
          target: windows
          
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - name: Build
        id: build
        shell: bash
        run: |
          flutter build ${{ matrix.config.target }}
          ls $PWD
          echo "output=$PWD/build/windows/x64/runner/Release" >> $GITHUB_OUTPUT
      - name: zzz
        uses: actions/upload-artifact@v4
        with:
          name: "build-${{ matrix.config.os }}"
          path: |
            ${{ steps.build.outputs.output }}/*.*
